use crate::domain::models::CommitId;

#[derive(Debug, Clone)]
pub enum Command {
    LoadRepo(Option<Vec<CommitId>>, usize, Option<String>),
    LoadRepoBackground(usize, Option<String>),
    LoadDiff(CommitId),
    DescribeRevision(CommitId, String),
    Commit(String),
    Snapshot,
    Edit(CommitId),
    Squash(Vec<CommitId>),
    New(CommitId),
    Abandon(Vec<CommitId>),
    Revert(Vec<CommitId>),
    Absorb,
    Duplicate(Vec<CommitId>),
    Parallelize(Vec<CommitId>),
    Rebase(Vec<CommitId>, String),
    SetBookmark(CommitId, String),
    DeleteBookmark(String),
    Split(CommitId),
    Undo,
    Redo,
    Fetch,
    Push(Option<String>),
    ResolveConflict(String),
    InitRepo,
    Evolog(CommitId),
    OperationLog,
}
